### ISSUE TITLE
Host this file as a website on my server?

### ISSUE THREAD

**Issue by VlaK0r** [PassPilot/PassPilot.com#2]
Hello! Thank you for your program.
Please tell me how I can host this file as a website on my server? So that the data would be stored on the server.

**Comment by PassPilot** [comment]
https://www.passpilot.com gives you this functionality where you can register and store data on the passpilot.com server, and I encourage you to do so but also have a local copy saved to a file every so often as a backup.
If you want to store data on your own server then you would have to modify the code to whatever server side application you want to create. You have to think of registration and authentication, will that be an internal server or exposed, whether to store the data in a database or file, communication encryption, server security etc. It depends on what suits your needs.
Still you can save your data to a complete PassPilot application file and each time upload it to a server, it will be safe there as the PassPilot file keeps the vault encrypted so no one can access your data from the file even if the server is compromised, but you would have to upload or overwrite an existing file each time when adding or modifying your passwords.
This repo gives you an offline application that you can save to a file so what you wrote is more of a question than an issue.
