### ISSUE TITLE
folders and tags

### ISSUE THREAD

**Issue by stransky87** [PassPilot/PassPilot.com#3]
Hi, could you please add the possibility of placing items in folders and also the possibility of adding tags to individual items?

**Comment by PassPilot** [comment]
Hi, this is as I understand for better items/passwords management and more efficient search? I will look into that but unfortunately it will not be soon as I am currently working simultaneously on another project in my spare time after hours. Expanding search and adding tags should be faster than folders but as soon as I work out some spare time I will do my best to add both features.

**Comment by PassPilot** [comment]
Thanks for suggesting the feature, I will close this item as it is not an actual issue for now.
